
jobs:
  include:
    - stage: Merge
      name: "Merge to main playlist"
      script:
        - echo "dummy job for merging"

after_success:
  - echo $TRAVIS_BUILD_STAGE_NAME
  - if [ "$TRAVIS_BUILD_STAGE_NAME" = "Merge" ]; then ./.travis/merge_if_success_test.sh |tee merge.log; fi

after_failure:
  - cat merge.log