# https://docs.travis-ci.com/user/docker/

jobs:
  include:
    - stage: Unit_test
      name: Test travis-docker-tryout

      services:
        - docker

      script:
        - docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1
        - sleep 60