# https://docs.travis-ci.com/user/docker/

jobs:
  include:
    - stage: Unit_test
      name: travis-appium-android-tryout/.travis.yml

      services:
        - docker

      install:
        # install docker compose
        - sudo rm -rf /usr/local/bin/docker-compose
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        - docker-compose --version

        # - docker-compose up -d

      script:
        - docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1
        - sleep 60
        - echo 'helloworld'
