
jobs:
  include:
    - stage: Test
      name: Test wget
      script:
        - cd $TRAVIS_BUILD_DIR/travis-wget
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/develop/travis-build-merger/_util/Pipfile
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/develop/travis-build-merger/_util/Pipfile.lock
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/develop/travis-build-merger/_util/merge.py
        - ls -l