language: generic

import:
  - credentials.yml

script:
  - hostname
  - mkdir /tmp/gh-pages-out

deploy:
  provider: pages
  local_dir: out
  github_token: $GITHUB_TOKEN
  local_dir: /tmp/gh-pages-out
