# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

version: ~> 1.0

os: linux
dist: bionic

language: node_js
node_js:
  - 12
cache:
  - npm
  - pip

import:
  - helloworld/.travis.yml
  - travis-broadcast/.travis.yml
  # - transfer-sh-tryout/.travis.yml
  # - travis-yml-import/test.yml
  # - travis-kicad-build/.travis.yml
  # # - build-stages-demo/.travis.yml
  # - travis-docker-tryout/.travis.yml
  # # - cache-docker-image/.travis.yml
  # - travis-build-docker-image/.travis.yml
  # - travis-arm-build/.travis.yml
  # - travis-pydrive-tryout/.travis.yml
  # - travis-wget/.travis.yml
  - merge/.travis.yml

notifications:
  slack:
    secure: VFA8yH986TdadSmOWgS7jOlp6t0uuBlKG3ObYTBF2qpAtqGDRDlY/zVA2tkonzwZh3JqYMZD164So8r9dU508/KrkAEf1qFH+sPt1Tn5eTsVETlmHECOBfD5UwP5iTsVuDVv3DBwnumHYptUcKxp+DqhoBKdVt7toVah3rR0luXfh/hyLMZJvGUwZqdczJfvTQHRFYbQBTV6/CDaE7zlRjnapNcB25V/OuLe/Vukcaow3gzJsm59bkCkeFRyeO70s7lB0YeaHjwa4H4KXWClq4MPH71HLDPLD+5LFgyqdkYe9FwjE4nyPSGjOMebSQYLlE0cUNwZCClQIvVmM5ep4wu+nzPruiqsQa+khzrmNfk/evpwh29saePA7/wwfBm8zKMVeVIiTXqRbOcNnmMrznGGTIWHt9XW2tl32ax55UZUxLoGZIG+LOd7SK6XHSwCcuW0rI5aen2smyK6uVB1KUiEWm4Cj0ETaWbPi1SOkhXUcvEAJuPtMZdGNxDPD8DphP9Pl6f5Qp0zaUsCbIDif5OHi1J5Ch5ICmJB1+bZMyFMEw4mcmhVOcFC/NxHheVjtsjzt9oPiIbirhBIWfHM9VpRP6lLteQAdI0VEyKRUBbx4jjNhogeZcbSqyYmB1G58z+14Hmpw6t0LC0wtVwnCgphRLok1HAQveyLbCvZEEU=

env:
  global:
    # GITHUB_TOKEN
    - secure: T5FMZIhIGap+LrNFrN4x1bDeUJ/LZWM/9tlDv0jbQ4V3iGob2FYYnBeOBTrXZrrft46/UZXZfLZ7rC4JqwbutTWxb5s79teFEe9OmhZGnVRldCpireKUrSFRNsjPTo4/vjkNI7x9/mmrF+SUKqtyJJy/vkbdVq97kzyBkH1OrsgoYTRtuSO2G4cbxT3Z10wq2PQrkjZp5rJNMdLT4Mw+MSgk/GcXnIbo3rVKLmUfmoTSkvy3232VDxycd6OB3/C+sdQsLRqCTkihe/pAosMQa28tmS+jL5Z6w1fkm7Yk2Ri4V+4ScX4xh3Vp6x12LoYMRLus7B1lkOc5auBe8ZuYmJAK6h3+9IooXXqL3dwZ+691F09TLmEUhfrRENLNe2DXbNiiyJPtabFnri1vlSXLSjzN4NWWeDYE6lwE65T9LjBAFibCRLrW5/TL0nCEoKRt4lftJNUZP3W3zcJK2l6MrbxVB2DN4W+yksHrwuhyL+dAZsxr+I42OcDGtDjbvfH6L6XjeawKVcLGdcK7x4dZLPyu2scpr1hntn4qs+Cf+yvqCYmBQRzPhM38vUhcakrypP/Iter/nsDhGXAamAtMrBY3CM4wYARkRBGvzm9+pbVYJUcBApnNhGi89UObv1syfzQ/MwEhWeHUGfxwNVsHbp1kRNe5m4gu+754do73AzE=

    # SLACK_TOKEN
    - secure: dCP2UJNEdIOtRJV7Psvh0Hoa9AnguYK8ZlEYQpVT7gqWXFbpt6/w5+YHs+tiAshVDYTAzwfVElGNP6+RD+L6wA7ruDooJsT038uYtpLyGZRAJfYfKHM05Lv4FbwcTnzq/6l07iPOXUryNw/cp+Q0XTXwxTjB0NbznyuwS1ygdMrRY12/HFBqQoPT7pFq8MgcP82TQOU5mRcRTo51nO3cyaFn0opKvp/SyzC4NY4+7orkcYAsWz4nr8VcmshH8Qd9MHCwhYDurINP4XvXarYP1XFdznSiMxCrQy+40WplBNt5s/NYntLn2EtNhGo1fQlcoJfscbMZaw6/6ezE/u4Na+Nf/qDobW1kP53aLBvCnGHx0y+Z+y624/wkPF+MUWcalNDI7XgXxVj5HSotj/6V8KwKuVNNFKJ6LZPUeqZ/HSB/uG+9Hh1bNhfvEEJo4f/pUgCd5iOTtqeZfpVQKLGJqRU4zjfUBaTT84SndudKFS/wtXIupzGIv67GEZA8LrTNfPuwgWlUiHjJWLQhoWngRnAbQy9pSoPN6lmpx4JBWwkjwMJhlg12lkS3icviDNFkwGCKEz3rVjpuuMB8kxdjIWiPqZSte6k+MoMqIects6pCYlxH957MrGtkk3rRF3ibz9ZrSWYD7X0idNEE7AOpcOYbyK/qcJ8PLuDZjIHXsr8=
