# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
# https://docs.travis-ci.com/user/conditions-v1

# You can import up to 25 other configs in total.

import:
  - travis-docker-selenium-tryout/.travis.yml
