sudo: required

services:
  - docker

language: generic

env:
  global:
    - NAME=myprojectname
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/${NAME}-${TRAVIS_COMMIT}.tgz

jobs:
  include:
    - stage: build
      script:
        - docker build -t ${IMAGE} ${PWD}
        - mkdir -p ${CACHE_FOLDER}
        - docker save ${IMAGE} | gzip -c > ${CACHE_FILE}
    - stage: push
      script:
        - ls -la ${CACHE_FOLDER}
        - if [[ -f ${CACHE_FILE} ]]; then docker load -i ${CACHE_FILE}; fi
        - docker images
        - echo "now you should see your image in the next stage, you can do what you wanted"

cache:
  bundler: true
  directories:
    - ${CACHE_FOLDER}
