# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

version: ~> 1.0

os: linux
dist: bionic

language: node_js
node_js:
  - 12
cache:
  - npm
  - pip


stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Merge
  - Integration_to_other_repo

import:
  - helloworld/.travis.yml
  # - travis-broadcast/.travis.yml
  - travis-conditional-build-tryout/.travis.yml
  # # - transfer-sh-tryout/.travis.yml
  # - travis-yml-import/test.yml
  # - travis-kicad-build/.travis.yml
  # # - build-stages-demo/.travis.yml
  # # - travis-docker-tryout/.travis.yml
  # # - cache-docker-image/.travis.yml
  # - travis-build-docker-image/.travis.yml
  # - travis-arm-build/.travis.yml
  # - travis-pydrive-tryout/.travis.yml
  # - travis-wget/.travis.yml
  - travis-build-merger/.travis.yml
  - Integration_to_other_repo/.travis.yml


notifications:
  slack:
    secure: VFA8yH986TdadSmOWgS7jOlp6t0uuBlKG3ObYTBF2qpAtqGDRDlY/zVA2tkonzwZh3JqYMZD164So8r9dU508/KrkAEf1qFH+sPt1Tn5eTsVETlmHECOBfD5UwP5iTsVuDVv3DBwnumHYptUcKxp+DqhoBKdVt7toVah3rR0luXfh/hyLMZJvGUwZqdczJfvTQHRFYbQBTV6/CDaE7zlRjnapNcB25V/OuLe/Vukcaow3gzJsm59bkCkeFRyeO70s7lB0YeaHjwa4H4KXWClq4MPH71HLDPLD+5LFgyqdkYe9FwjE4nyPSGjOMebSQYLlE0cUNwZCClQIvVmM5ep4wu+nzPruiqsQa+khzrmNfk/evpwh29saePA7/wwfBm8zKMVeVIiTXqRbOcNnmMrznGGTIWHt9XW2tl32ax55UZUxLoGZIG+LOd7SK6XHSwCcuW0rI5aen2smyK6uVB1KUiEWm4Cj0ETaWbPi1SOkhXUcvEAJuPtMZdGNxDPD8DphP9Pl6f5Qp0zaUsCbIDif5OHi1J5Ch5ICmJB1+bZMyFMEw4mcmhVOcFC/NxHheVjtsjzt9oPiIbirhBIWfHM9VpRP6lLteQAdI0VEyKRUBbx4jjNhogeZcbSqyYmB1G58z+14Hmpw6t0LC0wtVwnCgphRLok1HAQveyLbCvZEEU=

env:
  global:
    # TRAVIS_TOKEN
    - secure: "L9MoSrsdmKjzv8mQgG5fulJRHijs6XQk8afmBmeovUG9mWosNoD+WRYcb4fj0XzGT7B0j/tb3CbT028XIF1chBTGmJCQaG6hbO6ByrKgAlBHoo03TxxOT+8OgTCDJvZGLwAefNZXIR5nChp2mkXCZIQ8QRpVvrqEd7S4r+IBN2oeWJIzbVuGtqEkXViKBpHz/jk9ZzYrlZS5Lkt41jGhz2I3YRy70G0ccsmc9NFVrsb5mNTRKqLygbMTPcaMXdq3mm7s40odV9ZOUXUahHx3ZQKC7W2f+PaV3a0uF8Jy2qY518m+V1ZhCJvPujh9iXGVvLGjh7i+mt/rUURLjkoyaUnFD+kOWEO5E7GLO83zeEc28drxpC66LQ9g2f/32F7dvtyhbM3WoZqfQbbga8sc6V+eGH+L+xNnRVJUyR3Xc8B+GF9EpJEI2+FFr1H6poIoOIfp+5ml095HGJacYfoHVmDEiw7/oTO4rS9YwDGrqnEQbONgiYZTPRzEdM5+/6kCAmNleJdjP1LYj+lL6eYIHKwY+c9LjoJQJyrhwDhfljCbS4vO7rMxHdTB/9pwOThCubixQon7Ew4B3lskW2adtjEy6EgaIg4/ftQhTYHPdXa3sJ+hrQ9eWQqH3C0i48Ps337m1LSmAx2osy9ftCDG98IYZVgZEBRFbs68H+7AlZQ="

    # GITHUB_TOKEN
    - secure: T5FMZIhIGap+LrNFrN4x1bDeUJ/LZWM/9tlDv0jbQ4V3iGob2FYYnBeOBTrXZrrft46/UZXZfLZ7rC4JqwbutTWxb5s79teFEe9OmhZGnVRldCpireKUrSFRNsjPTo4/vjkNI7x9/mmrF+SUKqtyJJy/vkbdVq97kzyBkH1OrsgoYTRtuSO2G4cbxT3Z10wq2PQrkjZp5rJNMdLT4Mw+MSgk/GcXnIbo3rVKLmUfmoTSkvy3232VDxycd6OB3/C+sdQsLRqCTkihe/pAosMQa28tmS+jL5Z6w1fkm7Yk2Ri4V+4ScX4xh3Vp6x12LoYMRLus7B1lkOc5auBe8ZuYmJAK6h3+9IooXXqL3dwZ+691F09TLmEUhfrRENLNe2DXbNiiyJPtabFnri1vlSXLSjzN4NWWeDYE6lwE65T9LjBAFibCRLrW5/TL0nCEoKRt4lftJNUZP3W3zcJK2l6MrbxVB2DN4W+yksHrwuhyL+dAZsxr+I42OcDGtDjbvfH6L6XjeawKVcLGdcK7x4dZLPyu2scpr1hntn4qs+Cf+yvqCYmBQRzPhM38vUhcakrypP/Iter/nsDhGXAamAtMrBY3CM4wYARkRBGvzm9+pbVYJUcBApnNhGi89UObv1syfzQ/MwEhWeHUGfxwNVsHbp1kRNe5m4gu+754do73AzE=

    # SLACK_TOKEN, build-bot
    - secure: "AniVQbqCuM65vSq28MOZfLv6YlIfOBBf8gF3F3czkZjTDFd7ydcwmOe3YsxvGIO+qjnK9+a0z1yQiZyFgBnbm48sBZWxrcPd5SMXmCggjJYM4dTJYwZfel97gipx7XISUsejIvq0Mh0rCzBllMJjcW9Wk5P1ocaUPDffsTH0hqI7K4X/Q/Cslvuh6O66JeAcTIFFeE2YS6qlDBYN13mkym3MdRe487SqNs66h4aSSY5nKHYbipD5ePMWB0EdXffTzZVJ9xWFUYC9w41C1FhZRb3mzPOxF2tdoTwq6/rEscTYO6hAtehIRJK4CtoqotKtqBJ6QkuOvVMItmaPKklIIS4w+dPPgW14yQjCjk11hv+MXMswwmSCMu3NCXd3BSxHgVy7j5zaQTB74AnT7YbhrzskWXYDTQqeAQ8Ewz0kvUKZW/3pPMT756CKghDmmwYqJKM7gC47HxhOyszldaLJbabwprSehxWAhGK+vtvTR0DXkjvLSBy6ZIh455nL+Rdqp+lXbzqXZwpw+Yifpg7XvyWOxsHflAk+L32x/ZeiCB5KFfUxz3k3EOw7gB0xCVmkNd1+DUiMXXYpw0io+X7+DE15S9dLVgCSyC+UCEhJJhlqijBtmbYAPa0Z2LL29mrStDA8wtHhYMm9a1XIkzjT2bGq+dCXJ312+5E2G3s8crQ="