language: generic

import:
  - credentials.yml

script:
  - hostname
  - mkdir /tmp/gh-pages-out

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: /tmp/gh-pages-out
    github_token: $GITHUB_TOKEN
    on:
      branch: test/update-install-hugo