FROM ubuntu:18.04

# Install required software
# RUN apt-get update && \
#   apt-get install -y build-essential sudo git wget

RUN apt-get update
RUN apt-get install -y sudo
RUN apt-get install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
RUN python3 -m pip install pipenv

ENV PATH=$PATH:/root/.local/bin
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /root

# ENTRYPOINT ["echo travis-python"]