
# https://docs.travis-ci.com/user/docker/

jobs:
  include:
    - stage: Test
      name: Test-travis-build-docker-image
      arch:
        - arm64

      os: linux

      services:
        - docker

      before_install:
        - docker pull ubuntu:18.04

      script:
        - docker run ubuntu:18.04 hostname
