
jobs:
  include:
    - stage: Unit_test
      name: Sanity test
      script:
        - echo "helloworld"

# jobs:
#   include:
#     - stage: Merge
#       before_install:
#         - npm install remark-cli remark-validate-links

#       script:
#         - /bin/bash travis-test-markdown/ci-build.sh
