jobs:
  include:
    - stage: travis-broadcast
      script:
        # test travis broascast
        - cd $TRAVIS_BUILD_DIR/travis-broadcast
        - pipenv sync
        - pipenv run python3 travis-broadcast.py \#travis-build-result "this is apple"
