jobs:
  include:
    - stage: Test
      name: Test travis-broadcast
      script:
        - cd $TRAVIS_BUILD_DIR/travis-broadcast
        - ./broadcast_test.sh \#debug-travis-build-result "testing post to travis-build-result"
        - ./broadcast_test.sh debug-travis-need-help "$(./test_failed_message.sh)"
        - cd -
        # - cd .travis
        # - wget -O- https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-broadcast/broadcast.sh | bash - | tee broadcast.log
        # - cd -
