# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

jobs:
  include:
    - stage: Test
      name: bash_travis_yml_template
      script:
        - echo "helloworld"

    # # /home/logic/_workspace/travis-playlist/travis-build-merger/.travis.yml
    # - stage: Merge
    #   script:
    #     - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
    #     - bash merge_if_success.sh

stages:
  - name: Unit_test
  - name: Test
  - name: Build
  - name: Deploy

  - name: Integration_to_other_repo
    if: branch = develop

  - name: Publish_dashboard
    if: branch = master

  - name: Merge
    if: branch != master

  - name: Cron

# import:
#   - credentials.yml
