language: node_js
sudo: required

group: stable

jobs:
  include:
    - os: linux
      dist: focal

    - os: linux
      dist: bionic

    - os: linux
      dist: xenial

    - os: linux
      dist: trusty


script:
  #Display Firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
