# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
sudo: required

jobs:
  include:
      - os: linux
        dist: focal

      - os: linux
        dist: bionic

      - os: linux
        dist: xenial

      - os: linux
        dist: trusty

jobs:
  include:
    - stage: Build
      name: (tarvis-xvfb-tryout/.travis.yml)
      script:
        - echo helloworld

    - stage: Build1
      name: (tarvis-xvfb-tryout/.travis.yml)
      script:
        - echo helloworld
