# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
sudo: required

jobs:
  include:
    # - os: linux
    #   dist: focal

    # - os: linux
    #   dist: bionic
    - stage: Unit_test
      name: (tarvis-xvfb-tryout/.travis.yml)
      os: linux
      dist: xenial
      script:
        - echo helloworld

    - stage: Unit_test
      name: (tarvis-xvfb-tryout/.travis.yml)
      os: linux
      dist: bionic
      script:
        - echo helloworld
