# https://docs.travis-ci.com/user/gui-and-headless-browsers/
sudo: required

jobs:
  include:
    # - stage: Unit_test
    #   name: (tarvis-xvfb-tryout/.travis.yml)
    #   os: linux
    #   dist: focal
    #   script:
    #     - echo helloworld

    # - stage: Unit_test
    #   name: (tarvis-xvfb-tryout/.travis.yml)
    #   os: linux
    #   dist: bionic
    #   script:
    #     - echo helloworld

    # - stage: Unit_test
    #   name: (tarvis-xvfb-tryout/.travis.yml)
    #   os: linux
    #   dist: xenial
    #   script:
    #     - echo helloworld

    - stage: Unit_test
      name: (tarvis-xvfb-tryout/.travis.yml)
      os: linux
      dist: trusty
      script:
        #Display Firefox
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
