
jobs:
  include:
    - stage: Unit_test
      name: Sanity test (helloworld/.travis.yml)
      script:
        - echo "helloworld"

    - stage: test_helloworld_tryout
      name: Sanity test (helloworld/.travis.yml)
      script:
        - echo "helloworld"
