jobs:
  include:
    - stage: Cron
      name: travis-list-failed-branch (travis-list-failed-branch/.travis.yml)
      script:
        - cd travis-list-failed-branch
        -   yarn
        # -   node ./test_updateBuildFaliledList.js
        # -   node ./test_update_db.js
        -   node ./update-failed-list.js

        - cd ..
