jobs:
  include:
    - stage: transfer-sh tryout
      script:
        - cd $TRAVIS_BUILD_DIR/transfer-sh-tryout
        - id
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev p7zip-full curl
        - python3 transfer.py test.txt
