dist: bionic

script:
  - cd $TRAVIS_BUILD_DIR/travis-build-merger
  - id
  - sudo apt update
  - sudo apt install -y p7zip-full
  - 7za -p1233211234567 a test.7z test.txt -mx=9
  - curl --upload-file ./test.7z
