jobs:
  include:
    # TODO: move to Cron stage
    - stage: Test_cron
      name: daily snapshot (travis-daily-snapshot/.travis.yml)
      script:
        - cd travis-daily-snapshot
        -   node ./index.js
        - cd ..
