jobs:
  include:
    - stage: Cron
      name: daily snapshot (travis-daily-snapshot/.travis.yml)
      script:
        - cd travis-daily-snapshot
        -   yarn
        -   node ./update-statistics.js
        - cd ..
