# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

script:
  - echo "helloworld"

jobs:
  include:
    - stage: Build
      script:
        - cd travis-pipenv-helloworld
        - ./build.sh
        - cd ..

stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Integration_to_other_repo
  - Publish_dashboard
  - Merge
