# https://docs.travis-ci.com/user/docker/

jobs:
  include:
    # - stage: Test_cron
    #   name: Test travis-failed-rebuild-tryout
    #   script:
    #     - cd travis-failed-rebuild-tryout
    #     - yarn
    #     - node './index.js'

    - stage: Cron
      name: Cron travis-failed-rebuild-tryout
      script:
        - cd travis-failed-rebuild-tryout
        - yarn
        - node './index.js'