jobs:
  include:
    - stage: Unit_test
      name: travis-freecad-checking

      before_script:
        - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
        - sudo apt-get update
        - sudo apt-get install -y freecad freecad-python3
        - sudo mkdir /usr/lib/freecad-python3/Mod

      script:
        - for i in $(ls -1 *.FCStd); do python3 travis-freecad-checking/freecad_open_test.py $i; done

        # use case
        - mkdir .travis
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-freecad-checking/freecad_open_test.py -O .travis/freecad_open_test.py
        - for i in $(find . -name '*.FCStd'); do python3 .travis/freecad_open_test.py $i; done