# https://docs.travis-ci.com/user/docker/

jobs:
  include:
    - stage: Test
      name: Test travis-build-docker-image
      services:
        - docker
      before_install:
        - docker --version
      script:
        - cd travis-build-docker-image
        - docker build -t build-from-travis-helloworld .
        - cd -
