# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

jobs:
  include:
    - stage: Cron
      name: refactor travvis-yml tryout
      script:
        - cd travis-node-helloworld
        - ./build.sh
        - cd ..
