
jobs:
  include:
    - stage: Unit_test
      name: script test
      script:
        - sudo apt update
        - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv
        - pipenv sync
        - scripts/test_check_leak.sh
        # - mkdir -p .travis
        # - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-check-leak/check-leak.py .travis/check-leak.py
        # - python3 .travis/check-leak.py