
jobs:
  include:
    - stage: Unit_test
      name: test (travis-check-leak)
      before_script:
        - touch $HOME/.credentials.rc
      script:
        - sudo apt-get update
        - sudo apt-get install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
        - python3 -m pip install pipenv
        - pipenv sync

        - mkdir -p tmp
        - cd tmp
        -   rsync -avzh ../travis-check-leak/ .
        -   pipenv --rm || true
        -   pipenv sync
        -   pipenv run python3 main.py $TRAVIS_BUILD_DIR
        - cd ..

        - scripts/test_check_leak.sh $TRAVIS_BUILD_DIR
        # - mkdir -p .travis
        # - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-check-leak/check-leak.py .travis/check-leak.py
        # - python3 .travis/check-leak.py
