# https://docs.travis-ci.com/user/docker/

jobs:
  include:
    - stage: Test
      name: travis-docker-tryout

      services:
        - docker
      before_install:
        - docker pull ubuntu:18:04
      script:
        - docker run ubuntu:18:04 hostname
