
jobs:
  include:
    - stage: Test
      name: travis-conditional-build-tryout
      if: branch = "test/travis-conditional-build-tryout"
      script:
        - echo "helloworld"

    - stage: Test
      name: travis-conditional-build-tryout1
      if: branch = "test/travis-conditional-build-tryout1"
      script:
        - export TMP_DIR=$(mktemp -d)
        - cd $TMP_DIR
        - pwd
        - git clone  https://github.com/louiscklaw/travis-playlist.git  -b develop .
        - git branch
        - ls -l
        - echo "test test test test test "
        - cd -
