
jobs:
  include:
    - stage: Test
      name: travis-conditional-build-tryout
      script:
        if: branch = "test/travis-conditional-build-tryout"
          - echo "helloworld"
        if: branch = "test/travis-conditional-build-tryout1"
          - echo "test test test test test "
