
jobs:
  include:
    - stage: Test
      name: travis-conditional-build-tryout
      if: branch = "test/travis-conditional-build-tryout"
      script:
        - echo "helloworld"

    - stage: Test
      name: travis-conditional-build-tryout1
      if: branch = "test/travis-conditional-build-tryout1"
      script:
        - echo "test test test test test "
