# _config-examples/single-stage/.travis.yml
# https://testdriven.io/blog/faster-ci-builds-with-docker-cache/

jobs:
  include:
    - stage: travis-broadcast
      services:
        - docker
      before_script:
        - docker pull logickee/licheepi:latest || true
      script:
        - docker build --cache-from logickee/licheepi:latest --tag logickee/licheepi:latest .

      after_success:
        - docker login -u logickee -p $REGISTRY_PASS
        - docker push logickee/licheepi:latest

      cache:
        directories:
        - docker_images

      before_install:
        - docker load -i docker_images/images.tar || true

      before_cache:
        - docker images -a
        - docker save -o docker_images/images.tar $(docker images -a -q)
        - ls -l docker_images
