FROM ubuntu:18.04

# Install required software
# RUN apt-get update && \
#   apt-get install -y build-essential sudo git wget

# COPY sources.list.hk /etc/apt/sources.list

RUN apt-get update

RUN apt-get install -y sudo
RUN apt-get install -y libcurl4 curl


# https://github.com/nodesource/distributions
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential

RUN curl -sL https://firebase.tools | bash

ENV PATH=$PATH:/root/.local/bin
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /root

# # ENTRYPOINT ["echo travis-python"]a