dist: bionic

env:
  global:
    # GITHUB_TOKEN
    - secure: hqw3v4sCLVjEOFAMKWdtDrN5yVHsBdh8Ajtw7pJRE1bPJUA4rXfg2fs+f/hqqyQGUybtXvz6g7IgQPJpIrov9cHcd47qS27sfpvGAnbnbkkBGk+2lvBlvjnukipOaS7QZNQ2oyG96z1hLvmw/xLAaAWKstRDWxM1M8WkHJ7NHOqSj6OzIdzNb9KuBmCLoz8GDm05Temm4+kWADS/AElZN1aQPQIvEPl4Bnd54zlTqjBzKbGKSpsR7Ey7+lPteZ3IQ+mO1FnK2mYKwJ20EXz46xreoLCvy491xB1L5BADlDNICuyVLWND+Wbm41tMYpJtqNP8OIZ8/RNPW794RFIxnSJDehgbCqLmjSZrORoSBuu/UQ4XzIHf9/omV1qfj/3qV0ueXHJsQPHf84H+H3fhjXi88k4ac2OVtC9wvHeayZxGcuOqcF8M/13O2Fo84lXyFVbMxaplzwlLjv83atEG3BWIq4L3/veDn4Nx7GNtTjyEQsONI0DrBbPfANBjLQHJvFjmNmGg4PAt03Zq9W5zutaHLD+UNnHKaOexzsXoW6SvMOmNeC69qzgUgv4rIv5niivX6M1yU+hHZSuFaT1qqt7QJCp9uCQ/VNvng4KSNwfYtz+RNJpjAYf0R6UMT7Vhwoe+bMxhu2/S6jeOBYuwf2oKzmFe8bqRopLUrdB22lk=

    # SLACK_TOKEN
    - secure: mIMJSmDxvN2HHsoA4dhDhce7nz/UFQgZDqdKA348HWNXiwIdjDy3Tt1hsfSOUeXAz/SZBNZGUQuu0YsUNulCkub4C4boO9Ecrrb+ptodqKyNursiGDb+tAAVaUt/y3GMDMBthtJF53PPkKvqdtXwliYo9d2MW8y6WHnDRiQmdxcXS23+ngFdqDux3TTTplWxax6Sor+lKeetmD/Qf6557ty7/UjYv+z4z3LRwrJrWNKyJYfZA0oz9O59PgoHr64nTt/AZbWGMQvoWoAg16ONcZ7UEoxWb6RmF7V331rKyAPVhrrpS8dqAWgl1t30vOFM6bh/a4jZV4p5bVkV1uBiMEAYr2twkqi+w8uTCYsLlCpK1SjKVLKHzUdap9rGgtFRnrGVLv4x58lGoSJroDLbFULAUE5XEsggqxLH2SNeKOc3QZjBnvCOydZu7R8WynjY2FTmE+otUGqZ+MB9G1doTATxCMbstFlEo3b7tkhhLaDFf7WUQd9ol+F3x2fa22mdh2zfjNzD4rHTjEISbV3xhhLblo3lFE9UppT+fYWwms2srkBDHb34+u3WEz8rZwUUOTlJS2bTuSLxlKztbDf7cMkoSoYe9+e+iLzazAHFsrCzr8057tkv8V8nNQceQJxSdkC1RVBClY0ik+34m/P2zSuK2sGPrggO+8PhTGORxA8=

script:
  - id
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - pip3 install --user pipenv
  - pipenv sync
  - pipenv run python3 ./merge.py

notifications:
  slack: louislabs:x4D51HjnR30LGpqZXrdbqUgB