
jobs:
  include:
    - stage: Test
      script:
        - cd travis-build-merger
        - ./test/run_test.sh
        - cd ..
    - stage: Merge
      script:
        # the below should be kept for test inside travis-playlist only
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success_test.sh
        - bash merge_if_success_test.sh

        # production code
        # - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        # - bash merge_if_success.sh
