
jobs:
  include:
    - stage: Merge
      name: "travis-build-merger"
      script:
        - echo "dummy job for merging"
        - cd .travis
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/test/update-for-adding-handle-merge-to-master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh
        - cd -