# _config-examples/single-stage/.travis.yml
# https://testdriven.io/blog/faster-ci-builds-with-docker-cache/

jobs:
  include:
    - stage: travis-pull-docker-image
      services:
        - docker
      before_script:
        - docker pull hello-world || true
      script:
        - docker run hello-world

      cache:
        directories:
        - docker_images
